2018-02-25 21:34:29,358 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "MisOFF.py", line 152, in canciones
    letras , keys = read_db.lyrics(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 152, in lyrics
    data = reader(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 132, in reader
    song_id = tmp.find_one({"user_id":update.message.chat.id})["songId"]
KeyError: 'songId'
2018-02-25 21:34:50,619 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "MisOFF.py", line 146, in canciones
    if read_db.new_song(update):
  File "/home/rcancar/github/misonbot-/read_db.py", line 50, in new_song
    anterior_songId = tmp.find_one({"user_id":update.message.chat.id})["songId"]
KeyError: 'songId'
2018-02-25 21:35:39,150 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "MisOFF.py", line 152, in canciones
    letras , keys = read_db.lyrics(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 152, in lyrics
    data = reader(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 132, in reader
    song_id = tmp.find_one({"user_id":update.message.chat.id})["songId"]
KeyError: 'songId'
2018-02-25 21:36:13,740 - __main__ - INFO - User Ricardo canceled the conversation.
2018-02-25 21:36:27,477 - root - ERROR - no se pudo actualizar la pregunta estereotipo
Traceback (most recent call last):
  File "/home/rcancar/github/misonbot-/chat.py", line 109, in estereotipo
    "analisis.$[elemt].codigo_parrafo_estereotipo":tmp.find_one({'user_id':update.message.chat.id})["estro"],
TypeError: 'NoneType' object is not subscriptable
2018-02-25 21:39:56,321 - __main__ - INFO - User Ricardo canceled the conversation.
2018-02-25 21:40:09,648 - root - ERROR - no se pudo actualizar la pregunta estereotipo
Traceback (most recent call last):
  File "/home/rcancar/github/misonbot-/chat.py", line 110, in estereotipo
    "analisis.$[elemt].codigo_parrafo_estereotipo":tmp.find_one({'user_id':update.message.chat.id})["estro"],
TypeError: 'NoneType' object is not subscriptable
2018-02-25 21:40:43,815 - __main__ - INFO - User Ricardo canceled the conversation.
None
2018-02-25 22:14:56,302 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "MisOFF.py", line 152, in canciones
    letras , keys = read_db.lyrics(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 152, in lyrics
    data = reader(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 132, in reader
    song_id = tmp.find_one({"user_id":update.message.chat.id})["songId"]
KeyError: 'songId'
2018-02-25 22:15:03,243 - __main__ - INFO - User Ricardo canceled the conversation.
2018-02-25 22:15:06,609 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 295, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/rcancar/.local/lib/python3.6/site-packages/telegram/ext/regexhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "MisOFF.py", line 152, in canciones
    letras , keys = read_db.lyrics(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 152, in lyrics
    data = reader(update)
  File "/home/rcancar/github/misonbot-/read_db.py", line 132, in reader
    song_id = tmp.find_one({"user_id":update.message.chat.id})["songId"]
KeyError: 'songId'
{'_id': ObjectId('5a932877e1382344d1e7dcc1'), 'user_id': 500737046, 'genero': 'rom√°ntica', 'songId': 30003, 'estro': [1, 2, 3]}
